#! /usr/bin/env python
import sys, libxml2
def open(xml_file):
  doc = libxml2.parseFile(xml_file)
  root = doc.getRootElement()
  child = root.children
  child = child.children
  child = child.children
  child = child.children
  while child.next is not None :
   print child.content
   child =child.next
def main(argv):
  if len(argv) != 2:
    sys.stderr.write("Usage : %s xml_file" % (argv[0],))
  else:    open(argv[1])
if __name__ == '__main__': main(sys.argv)

